package array.string;

import java.lang.reflect.Array;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

import talentcode23.C;

// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

// Example 1:

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
// Example 2:

// Input: s = "", t = "y"
// Output: "y"

// Constraints:

// 0 <= s.length <= 1000
// t.length == s.length + 1
// s and t consist of lowercase English letters.

public class FindTheDifference {
    //ASCII number approach
    public static char findTheDifference1(String s, String t) {
        int a = 0;
        int b = 0;
        int i = 0;
        while (i < s.length() || i < t.length()) {
            if (i < s.length()) {
                a += s.charAt(i);
            }
            if (i < t.length()) {
                b += t.charAt(i);
            }
            i++;
        }

        return (char) (b - a);
    }

    public static void main(String[] args) {
        System.out.println("Test case 1 (expected e): " + findTheDifference2("abcd", "abcde"));
        System.out.println("Test case 2 (expected e): " + findTheDifference2("adbc", "abecd"));
        System.out.println("Test case 3 (expected e): " + findTheDifference2("abcd", "ebacd"));
        System.out.println("Test case 4 (expected a): " + findTheDifference2("a", "aa"));
        System.out.println("Test case 5 (expected a): " + findTheDifference2("ae", "aea"));
    }
}
